nenga/address/urls.py
# -*- coding: utf-8 -*-
"""routing of nenga.address."""
from django.conf.urls import patterns, url


urlpatterns = patterns('nenga.address.views',
                       url(r'^$', 'index', name='index'),
                       url(r'^profile/$', 'profile', name='profile'),
                       url(r'^contacts/$', 'contacts', name='contacts'),
                       url(r'^contacts/(?P<pk>\w+)/$', 'contact_edit',
                           name='contact_edit'),
                       url(r'^plan_actual/$', 'plan_actual',
                           name='plan_actual'),
                       url(r'^plan_actual/(?P<year>\d{4})/$', 'plan_actual',
                           name='plan_actuals'),
                       url(r'^plan_actual/(?P<pk>\w+)/$',
                           'plan_actual_edit',
                           name='plan_actual_edit'),)

nenga/core/urls.py
# -*- coding: utf-8 -*-
"""basic routing of Nenga as Django App."""
from django.conf.urls import patterns, include, url
from django.views.generic import RedirectView
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
                       (r'^$', RedirectView.as_view(url='/nenga/',
                                                    permanent=True)),
                       (r'^login/$', 'django.contrib.auth.views.login',
                        {'template_name': 'address/login.html'}),
                       (r'^logout/$', 'django.contrib.auth.views.logout',
                        {'template_name': 'address/logout.html'}),
                       (r'^nenga/', include('nenga.address.urls')),
                       url(r'^admin/', include(admin.site.urls)),)

nenga/address/models.py
# -*- coding: utf-8 -*-
"""models of nenga.address."""
import sys
from django.db import models
from django.contrib.auth.models import User
from shortuuidfield import ShortUUIDField
import jsonfield
from nenga.queryset.models import PrivateQuerySet, YearQuerySet
from model_utils.managers import PassThroughManager


class BaseObject(models.Model):
    """Abstract base model that had id attribute formatted as shortuuid."""

    id = ShortUUIDField(primary_key=True, auto=True, verbose_name='UUID')

    class Meta(object):
        """meta class of BaseObject."""

        abstract = True


class PrivateObject(BaseObject):
    """Abstract private model that extend with owner to BaseObject."""

    owner = models.ForeignKey(User, blank=False, null=True,
                              on_delete=models.SET_NULL)

    class Meta(object):
        """meta class of PrivateObject."""

        abstract = True


class Contact(PrivateObject):
    """Contact model."""

    PREFECTURE_CHOICES = [
        ('01', '北海道'),
        ('02', '青森県'),
        ('03', '岩手県'),
        ('04', '宮城県'),
        ('05', '秋田県'),
        ('06', '山形県'),
        ('07', '福島県'),
        ('08', '茨城県'),
        ('09', '栃木県'),
        ('10', '群馬県'),
        ('11', '埼玉県'),
        ('12', '千葉県'),
        ('13', '東京都'),
        ('14', '神奈川県'),
        ('15', '新潟県'),
        ('16', '富山県'),
        ('17', '石川県'),
        ('18', '福井県'),
        ('19', '山梨県'),
        ('20', '長野県'),
        ('21', '岐阜県'),
        ('22', '静岡県'),
        ('23', '愛知県'),
        ('24', '三重県'),
        ('25', '滋賀県'),
        ('26', '京都府'),
        ('27', '大阪府'),
        ('28', '兵庫県'),
        ('29', '奈良県'),
        ('30', '和歌山県'),
        ('31', '鳥取県'),
        ('32', '島根県'),
        ('33', '岡山県'),
        ('34', '広島県'),
        ('35', '山口県'),
        ('36', '徳島県'),
        ('37', '香川県'),
        ('38', '愛媛県'),
        ('39', '高知県'),
        ('40', '福岡県'),
        ('41', '佐賀県'),
        ('42', '長崎県'),
        ('43', '熊本県'),
        ('44', '大分県'),
        ('45', '宮崎県'),
        ('46', '鹿児島県'),
        ('47', '沖縄県')]
    last_name = models.CharField(max_length=255, unique=False)
    first_name = models.CharField(max_length=255, unique=False)
    zip_code = models.CharField(max_length=7, blank=False)
    prefecture = models.CharField(max_length=2, choices=PREFECTURE_CHOICES)
    city = models.CharField(max_length=255, unique=True)
    address = models.CharField(max_length=255, unique=False)
    address2 = models.CharField(max_length=255, unique=False,
                                blank=True, default="")
    partner_name = models.CharField(max_length=255, unique=False,
                                    blank=True, default="")
    objects = PassThroughManager.for_queryset_class(PrivateQuerySet)()

    class Meta(object):
        """meta class of Contact."""

        db_table = 'contact'
        unique_together = ('last_name', 'first_name', 'address',
                           'zip_code', 'owner')
        permissions = (
            ('view_contact', 'View contact'),
            )

    def __unicode__(self):
        """unicode()."""
        return "%s %s" % (self.last_name, self.first_name)

    def __str__(self):
        """str()."""
        return "%s %s" % (self.last_name, self.first_name)


class Year(models.Model):
    """Year."""

    year = models.DecimalField(max_digits=4, decimal_places=0, unique=True)
    objects = PassThroughManager.for_queryset_class(YearQuerySet)()

    class Meta(object):
        """meta class of Year."""

        db_table = 'year'

    def __unicode__(self):
        """unicode()."""
        return str(self.year)

    def __str__(self):
        """str()."""
        return str(self.year)


class PlanActual(PrivateObject):
    """plan and actual."""

    destination = models.ForeignKey(Contact)
    year = models.ForeignKey(Year)
    plan = models.BooleanField(default=True)
    actual = models.NullBooleanField(default=None)
    objects = PassThroughManager.for_queryset_class(PrivateQuerySet)()

    class Meta(object):
        """meta class of PlanActual."""

        db_table = 'plan_actual'
        unique_together = ('destination', 'year', 'owner')
        permissions = (
            ('view_plan_actual', 'View PlanActual'),
            )

    def __unicode__(self):
        """unicode()."""
        if sys.version_info < (3, 0):
            return unicode(self.destination)
        else:
            return str(self.destination)

    def __str__(self):
        """str()."""
        return str(self.destination)


class BackLayout(PrivateObject):
    """Back layout AKA "Ura-men"."""

    year = models.ForeignKey(Year)
    layout_template = models.TextField()
    template_attributes = jsonfield.JSONField()

    class Meta(object):
        """meta class of BackLayout."""

        db_table = 'back_layout'
        unique_together = ('year', 'owner')
        permissions = (
            ('view_back_layout', 'View BackLayout'),
            )

    def __unicode__(self):
        """unicode."""
        if sys.version_info < (3, 0):
            return unicode(self.year)
        else:
            return str(self.year)

    def __str__(self):
        """str()."""
        if sys.version_info < (3, 0):
            return unicode(self.year)
        else:
            return str(self.year)

nenga/address/forms.py
# -*- coding: utf-8 -*-
"""forms of nenga.address."""
from django.forms import ModelForm, HiddenInput
from nenga.address.models import Contact, PlanActual


class ContactForm(ModelForm):
    """ModelForm of Contact."""

    class Meta(object):
        """meta class of ContactForm."""

        model = Contact
        fields = ('last_name',
                  'first_name',
                  'zip_code',
                  'prefecture',
                  'city',
                  'address',
                  'address2',
                  'partner_name',
                  'owner')

        widgets = {'owner': HiddenInput()}


class PlanActualForm(ModelForm):
    """ModelForm of PlanActual."""

    class Meta(object):
        """meta class of PlanActualForm."""

        model = PlanActual
        fields = ('destination',
                  'year',
                  'plan',
                  'actual',
                  'owner')

        widgets = {'owner': HiddenInput()}

nenga/address/views.py
# -*- coding: utf-8 -*-
"""views of nenga.address."""
from django.shortcuts import render_to_response
from django.forms.models import modelformset_factory
from django.http import HttpResponseRedirect
from django.template import RequestContext
from nenga.address.models import Contact, PlanActual, Year
from nenga.address.forms import ContactForm, PlanActualForm


def index(request):
    """index view."""
    return render_to_response('address/index.html',
                              {'is_authenticated':
                               request.user.is_authenticated()},
                              context_instance=RequestContext(request))


def profile(request):
    """profile view."""
    return render_to_response('address/profile_detail.html',
                              {'is_authenticated':
                               request.user.is_authenticated()},
                              context_instance=RequestContext(request))


def contacts(request):
    """list view of contacts."""
    contacts = Contact.objects.owned_list(request.user)

    return render_to_response('address/contact_list.html',
                              {'is_authenticated':
                               request.user.is_authenticated(),
                               'contacts': contacts},
                              context_instance=RequestContext(request))


def contact_edit(request, pk):
    """edit view of contact."""
    ContactFormSet = modelformset_factory(
        model=Contact,
        form=ContactForm)
    if request.method == 'POST':
        formset = ContactFormSet(request.POST)
        if formset.is_valid():
            formset.save()
            return HttpResponseRedirect('/nenga/contacts')
    else:
        formset = modelformset_factory(
            model=Contact,
            form=ContactForm,
            max_num=1,
            extra=1,
            )(queryset=Contact.objects.filter(id=pk))

    return render_to_response('address/contact_edit.html',
                              {'is_authenticated':
                               request.user.is_authenticated(),
                               'formset': formset},
                              context_instance=RequestContext(request))


def plan_actual(request, year=None):
    """list view of plan and actual."""
    years = Year.objects.all()
    if year:
        plan_actuals = PlanActual.objects.owned_list_by_year(request.user,
                                                             year)
    else:
        plan_actuals = PlanActual.objects.owned_list(request.user)
    return render_to_response('address/plan_actual_list.html',
                              {'is_authenticated':
                               request.user.is_authenticated(),
                               'years': years,
                               'plan_actuals': plan_actuals},
                              context_instance=RequestContext(request))


def plan_actual_edit(request, pk):
    """edit view of plan_actual."""
    PlanActualFormSet = modelformset_factory(
        model=PlanActual,
        form=PlanActualForm)
    if request.method == 'POST':
        formset = PlanActualFormSet(request.POST)
        if formset.is_valid():
            formset.save()
            return HttpResponseRedirect('/nenga/plan_actual/')
    else:
        formset = modelformset_factory(
            model=PlanActual,
            form=PlanActualForm,
            max_num=1,
            extra=1,
        )(queryset=PlanActual.objects.filter(id=pk))

    return render_to_response('address/plan_actual_edit.html',
                              {'is_authenticated':
                               request.user.is_authenticated(),
                               'formset': formset},
                              context_instance=RequestContext(request))

nenga/templates/address/contact_edit.html
{% extends "layout.html" %}
{% block content %}
<div class="row">
  <form method="post">
    {% csrf_token %}
    <fieldset>
    {{ formset.management_form }}
    {% for form in formset %}
    {% for field in form %}
      <div class="form-group">
        {% if field.label != "Id" %}
        {{ field.label_tag }}
        {% endif %}
        {{ field }}
      </div>
    {% endfor %}
    {% endfor %}
    </fieldset>
    <input type="submit" value="update"/>
  </form>
</div>
{% endblock %}

nenga/templates/address/contact_list.html
{% extends "layout.html" %}
{% block content %}
<div class="row">
  <table class="table table-condensed">
    <thead>
      <tr>
        <td>Name</td>
        <td>Zip code</td>
        <td>Address</td>
        <td></td>
      </tr>
    </thead>
    <tbody>
      {% for contact in contacts %}
      <tr class="">
        <td>{{ contact.last_name }} {{ contact.first_name }}</td>
        <td>{{ contact.zip_code }}</td>
        <td>{{ contact.get_prefecture_display }} {{ contact.city }} {{ contact.address }} {{ contact.address2 }}</td>
        <td><a href="/nenga/contacts/{{ contact.id }}/" class="btn btn-primary">Edit</a></td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
  <hr/>
  <ul class="pager"></ul>
</div>
{% endblock %}

nenga/templates/address/contacts.html
{% extends "layout.html" %}
{% block content %}
<div class="row">
  <table class="table table=condensed">
    <thead>
      <tr>
        <td>Name</td>
        <td>Zip code</td>
        <td>Address</td>
      </tr>
    </thead>
    <tbody>
      {% for contact in contacts %}
      <tr class="">
        <td>{{ contact.last_name }} {{ contact.first_name }}</td>
        <td>{{ contact.zip_code }}</td>
        <td>{{ contact.get_prefecture_display }} {{ contact.city }} {{ contact.address }} {{ contact.address2 }}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
  <hr/>
  <ul class="pager"></ul>
</div>
{% endblock %}

nenga/templates/address/index.html
{% extends "layout.html" %}
{% block content %}
<div class="row">
  <hr/>
  <ul class="pager"></ul>
</div>
{% endblock %}

nenga/templates/address/login.html
{% extends "layout.html" %}
{% block content %}
<div class="row">
  <form method="post" action="{% url 'django.contrib.auth.views.login' %}">
    {% csrf_token %}
    <div class="input-group">
      <span class="input-group-addon">username</span>
      <input id="username" name="username" class="form-control" type="text" placeholder="Input your account name"/>
    </div>
    <div class="input-group">
      <span class="input-group-addon">password</span>
      <input id="password" name="password" class="form-control" type="password"/>
    </div>
    <input id="submit" type="submit" class="btn btn-default" value="login"/>
    <input type="hidden" name="next" value="{{ next }}"/>
  </form>
</div>
{% endblock %}

nenga/templates/address/logout.html
{% extends "layout.html" %}
{% block content %}
<div class="row">
  <p>Your account logged out.</p>
  <p><a href="/login">Log in with your account.</a></p>
</div>
{% endblock %}

nenga/templates/address/plan_actual_edit.html
{% extends "layout.html" %}
{% block content %}
<div class="row">
  <form method="post">
    {% csrf_token %}
    <fieldset>
    {{ formset.management_form }}
    {% for form in formset %}
    {% for field in form %}
      <div class="form-group">
        {% if field.label != "Id" %}
        {{ field.label_tag }}
        {% endif %}
        {{ field }}
      </div>
    {% endfor %}
    {% endfor %}
    </fieldset>
    <input type="submit" value="update"/>
  </form>
</div>
{% endblock %}

nenga/templates/address/plan_actual_list.html
{% extends "layout.html" %}
{% block content %}
<div class="row">
  <div class="col-md-2">
    <select id="year" class="form-control">
      <option value="">select year</option>
      {% for year in years %}
      {% if year %}<option value="{{ year }}">{{ year }}</option>{% endif %}
      {% endfor %}
    </select>
  </div>
  <table class="table table-condensed">
    <thead>
      <tr>
        <td>Name</td>
        <td>Year</td>
        <td>Plan</td>
        <td>Actual</td>
        <td></td>
      </tr>
    </thead>
    <tbody>
      {% for list in plan_actuals %}
      <tr class="">
        <td>{{ list.destination }}</td>
        <td>{{ list.year }}</td>
        <td>{{ list.plan }}</td>
        <td>{{ list.actual }}</td>
        <td><a href="/nenga/plan_actual/{{ list.id }}/" class="btn btn-primary">Edit</a></td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
  <hr/>
  <ul class="pager"></ul>
</div>
{% endblock %}

nenga/templates/address/profile_detail.html
{% extends "layout.html" %}
{% block content %}
<div class="row">
  <table class="table table-hover">
    <tr><td>User account</td><td>{{ user.username }}</td></tr>
    <tr><td>Full name</td><td>{{ user.get_full_name }}</td></tr>
    <tr><td>E-mail</td><td>{{ user.email }}</td></tr>
    <tr><td>Joined date</td><td>{{ user.date_joined }}</td></tr>
    <tr><td>Last login</td><td>{{ user.last_login }}</td></tr>
  </table>
</div>
{% endblock %}